CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Admins" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("Id")
);

CREATE TABLE "Clients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "SecondName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Balance" numeric(12,2) NOT NULL,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("Id")
);

CREATE TABLE "Rates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Value" numeric NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Rates" PRIMARY KEY ("Id")
);

CREATE TABLE "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Amount" numeric(12,2) NOT NULL,
    "Status" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "ClientId" integer NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Clients_Email" ON "Clients" ("Email");

CREATE INDEX "IX_Payments_ClientId" ON "Payments" ("ClientId");

CREATE INDEX "IX_Payments_Date" ON "Payments" ("Date");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250622170225_InitialMigration', '8.0.17');

COMMIT;

